if (self.CavalryLogger) { CavalryLogger.start_js(["8sQRT"]); }

__d("MWChatForceCollapseTabs.bs",["bs_block","React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,b("bs_block").__(5,[a]));else return 0},[d,c])}f.useHook=a}),null);
__d("MWChatForceCollapseTabs.re",["MWChatForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.bs",["bs_block","React","MWChatMultitabContext.bs","MWChatMultitabDispatcher.bs","useCometFeedNoRoutingNavigationEventLogger"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c=b("useCometFeedNoRoutingNavigationEventLogger")(),d=g.useContext(b("MWChatMultitabContext.bs").context);return g.useCallback(function(a){c(Date.now(),"","messenger");if(d!==void 0)return b("MWChatMultitabDispatcher.bs").dispatch(void 0,d,b("bs_block").__(6,[a]));else return 0},[d,c])}f.useHook=a}),null);
__d("MWChatUndoForceCollapseTabs.re",["MWChatUndoForceCollapseTabs.bs"],(function(a,b,c,d,e,f){a=b("MWChatUndoForceCollapseTabs.bs").useHook;f.useHook=a}),null);
__d("useToggleChatTabsOnMountUnmount",["CometRouteRenderType","MWChatForceCollapseTabs.re","MWChatUndoForceCollapseTabs.re","React","useShouldShowMessagingEntrypointOnCurrentRoute"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a=b("useShouldShowMessagingEntrypointOnCurrentRoute")("CHAT"),c=b("CometRouteRenderType").useIsPushView(),d=b("MWChatForceCollapseTabs.re").useHook(),e=b("MWChatUndoForceCollapseTabs.re").useHook();g.useEffect(function(){a&&d(c);return function(){a&&e(c)}},[a,c,d,e])}}),null);
__d("useLiveVideoCometInstreamRewardAlertDisplay",["createVideoStateHook"],(function(a,b,c,d,e,f){"use strict";a=b("createVideoStateHook").createVideoStateHook(null);c=a.setterHook;d=a.valueHook;e=c;f.useInstreamRewardAlertDisplayStateSetter=e;b=d;f.useInstreamRewardAlertDisplayStateValue=b}),null);
__d("validateTrackingCode",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="object"&&a.click_tracking_linkshim_cb!=null&&a.encrypted_click_tracking!=null&&a.encrypted_tracking!=null?a:null}}),null);
__d("validateAggregatedStoryTrackingNodeIndex",[],(function(a,b,c,d,e,f){"use strict";e.exports=a;function a(a){return a!=null&&typeof a==="number"?a:0}}),null);
__d("CometVideoCommentComposerGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a){a=a.index;return g.jsx("div",{className:"j9ispegn pmk7jnqg dhix69tm bi6gxh9e wkznzc2l kvgmc6g5 n7fi1qx3 i09qtzwb",children:g.jsxs("div",{className:"j83agx80 bp9cbjyn",children:[g.jsx(b("BaseGlimmer.react"),{className:"q676j6op oi9244e8 qypqp5cg pfnyh3mw spb7xbtv bkmhp75w emlxlaya s45kfl79",index:a}),g.jsx(b("BaseGlimmer.react"),{className:"l5sxq0ai tv7at329 buofh1pr gob819ct ols5edhi gmcszhul emml16de",index:a})]})})}}),null);
__d("CometVideoProfileInfoGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(a){var c;a=a.index;return g.jsxs("div",{className:"cbu4d94t j83agx80",children:[g.jsxs("div",{className:"j83agx80",children:[g.jsx(c=b("BaseGlimmer.react"),{className:"go5t5npl oi9244e8 hxdsxuhi spb7xbtv bkmhp75w emlxlaya s45kfl79",index:a}),g.jsxs("div",{className:"taijpn5t cbu4d94t j83agx80",children:[g.jsx(c,{className:"elpiyq4v bi6gxh9e cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:a}),g.jsx(c,{className:"i7o4yfgj cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:a})]})]}),g.jsx(c,{className:"f4c7eilb n1l5q3vz jnigpg78 ns4ygwem fykbt5ly hgaippwi fni8adji",index:a})]})}}),null);
__d("CometTahoeUpNextItemGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){var a;return g.jsxs("div",{className:"tr9rh885 j83agx80",children:[g.jsx(a=b("BaseGlimmer.react"),{className:"m7fg4r8v tvfksri0 ic2jb53e qttc61fc ihh4hy1g kdgqqoy6 jk6sbkaj",index:0}),g.jsxs("div",{children:[g.jsx(a,{className:"bow6oqyw gl3lb2sf l82x9zwi uo3d90p7 pw54ja7n ue3kfks5",index:0}),g.jsx(a,{className:"nx96mzau ku2m03ct cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:0}),g.jsx(a,{className:"lelwyktv ku2m03ct cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:0})]})]})}}),null);
__d("CometTahoeUpNextGlimmer.react",["BaseGlimmer.react","CometTahoeUpNextItemGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React"),h=3;function a(){return g.jsxs("div",{className:"cbu4d94t j83agx80",children:[g.jsx(b("BaseGlimmer.react"),{className:"bow6oqyw gl3lb2sf l82x9zwi uo3d90p7 pw54ja7n ue3kfks5",index:0}),Array(h).fill().map(function(a,c){return g.jsx(b("CometTahoeUpNextItemGlimmer.react"),{},c)})]})}}),null);
__d("CometTahoeSidePaneGlimmer.react",["CometTahoeUpNextGlimmer.react","CometVideoCommentComposerGlimmer.react","CometVideoProfileInfoGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("React");function a(){return g.jsxs("div",{className:"dhix69tm sjgh65i0 wkznzc2l tr9rh885 cbu4d94t j83agx80",children:[g.jsx("div",{className:"tfnaxnde",children:g.jsx(b("CometVideoProfileInfoGlimmer.react"),{index:0})}),g.jsx(b("CometTahoeUpNextGlimmer.react"),{}),g.jsx("div",{className:"pmk7jnqg lfi1tu6t",children:g.jsx(b("CometVideoCommentComposerGlimmer.react"),{index:0})})]})}}),null);